### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Martmists-GH** [AndroidAudioMods/ViPERFX_RE#2]
Effects:

- [x] AnalogX
- [ ] ColorfulMusic
- [ ] Convolver
- [x] Cure
- [x] DiffSurround
- [x] DynamicSystem
- [ ] FETCompressor
- [ ] IIRFilter
- [ ] PlaybackGain
- [x] Reverberation
- [x] SpeakerCorrection
- [x] SpectrumExtend
- [x] TubeSimulator
- [ ] VHE
- [x] ViPERBass
- [x] ViPERClarity
- [ ] ViPERDDC

Utilities:

- [x] AdaptiveBuffer_FPI32
- [x] CAllpassFilter
- [x] CCombFilter
- [x] CRevModel
- [x] Crossfeed
- [x] DepthSurround
- [x] DynamicBass
- [ ] FIR
- [x] FixedBiquad
- [ ] Harmonic
- [x] HiFi
- [x] HighShelf
- [x] IIR_1st
- [x] IIR_NOrder_BW_BP
- [x] IIR_NOrder_BW_LH
- [ ] MinPhaseIIRCoeffs
- [x] MultiBiquad
- [x] NoiseSharpening
- [x] PassFilter
- [ ] PConvSingle_F32
- [x] PolesFilter
- [x] Polyphase
- [x] SoftwareLimiter
- [ ] Stereo3DSurround
- [x] Subwoofer
- [x] TimeConstDelay
- [x] WaveBuffer_I32

Core:

- [ ] Effect 
- [ ] ProcessUnit_FX

Unused:

- [ ] AdaptiveBuffer_R32
- [ ] eFilter
- [ ] FIREqualizer
- [ ] FFT_R24_F32
- [ ] WaveBuffer_R32 (Deprecated by making WaveBuffer_I32 use floats)

**Comment by iscle** [comment]
Seemingly working as expected effects:

- [x] Master limiter
    - [x] Output gain
    - [x] Output pan
    - [x] Threshold limit 
- [ ] Playback gain control
- [ ] FET compressor
- [x] ViPER-DDC
- [x] Spectrum extension
- [x] FIR equalizer
- [ ] Convolver
- [ ] Field surround
- [x] Differential surround
- [ ] Headphone surround +
- [ ] Reverberation
- [x] Dynamic system
- [x] Tube simulator (6N1J)
- [x] ViPER bass
    - [x] Natural bass
    - [x] Pure bass +
    - [x] Subwoofer
- [x] ViPER clarity
    - [x] Natural
    - [x] OZone+
    - [x] XHiFi
- [x] Auditory system protection
- [x] AnalogX
- [x] Speaker optimization

**Comment by Ko-Hi-Dev** [comment]
Why is for equalizer llsted as unused?

**Comment by iscle** [comment]
> Why is for equalizer llsted as unused?

FIREqualized is not being used, they used IIRFilter instead.

**Comment by Ko-Hi-Dev** [comment]
> > Why is for equalizer llsted as unused?
> 
> FIREqualized is not being used, they used IIRFilter instead.

Are you sure? Because i never used any IIRfilter. Or are you saying that their *Equalizer* was just using IIRFILTER ? Because it felt like it was an equalizer. But you can be right.

So it will be removed?

**Comment by Martmists-GH** [comment]
> > > Why is for equalizer llsted as unused?
> > 
> > 
> > FIREqualized is not being used, they used IIRFilter instead.
> 
> Are you sure? Because i never used any IIRfilter. Or are you saying that their _Equalizer_ was just using IIRFILTER ? Because it felt like it was an equalizer. But you can be right.
> 
> So it will be removed?

The FIREqualizer class did not seem to be used if I recall correctly. We're trying to port it functionally 1:1, so we likely won't look into unused classes.

**Comment by nift4** [comment]
any chance "Seemingly working as expected effects" can be updated again? last edit was in october

**Comment by iscle** [comment]
> any chance "Seemingly working as expected effects" can be updated again? last edit was in october

Still the same, except AnalogX which is also working now. There will be an alpha release on 01/01/2023 at 00:00 GMT+1, keep an eye on the Telegram channel. (https://t.me/ViPER4AndroidFXchannel)

**Comment by devnoname120** [comment]
`ViPERDDC` is available now, the checkbox can be ticked. As far as I know `Auditory system protection` works too, I'm not sure when support was added though.

**Comment by tg2sipfork** [comment]
@Martmists-GH @iscle 

https://github.com/Audio4Linux/Viper4Linuxx-GUI
https://github.com/Audio4Linux/Viper4Linux
https://github.com/Audio4Linux/JDSP4Linux

maybe this code will help to fix Convolver?

### **also maybe its possible to add "audio Recinsruct" fucntionnal to new ViperFX?**

its name as

### viper4android.headphone_xhifi.xfisound.process
### viper4android.headphone_xhifi.xfisound.locontour

```
viper4android.headphone_xhifi.xfisound.process
viper4android.headphone_xhifi.xfisound.locontour

```

its Driver code
maybe it's possible to reverse engineer it?
https://github.com/vipersaudio/viper4android_xhifi/tree/master/android_4.x/assets

from here
https://github.com/Zackptg5/ViPER4Android-XHiFi
https://github.com/vipersaudio/viper4android_xhifi

this app - ViPER4Android-XHiFi - works only on old phones like LG G8 and V30 on android 12L 

so am ready to pay for port this functional to new Viper or just fot update this app for work on modern android 14+


![image](https://github.com/user-attachments/assets/2ff35598-a89b-4d0f-8f50-1ecf1f57c766)
![image](https://github.com/user-attachments/assets/1e65dfab-d59c-4cb9-82a1-6b42ab13a198)


thanks

**Comment by JQF-241** [comment]
Can Big Brother adapt to A15?

**Comment by k9online** [comment]
Working on A15 for me. crDroid on OnePlus 7 Pro using "legacy" mode.

**NOTE: This is with the slightly updated fork https://github.com/WSTxda/ViperFX-RE-Releases
However from what I understand, nothing they did should have aided in compatibility with A15. They did improve on a couple things (at least it says they have) and added Reverberation.

**Comment by devnoname120** [comment]
Yeah it works for me with legacy. I haven't tried the other mode but it has always been more on-and-off than legacy (I'm not sure what the purpose is compared to just using legacy…)

**Comment by tg2sipfork** [comment]
any link for donations?

**Comment by devnoname120** [comment]
@tg2sipfork https://github.com/sponsors/iscle

**Comment by Martmists-GH** [comment]
Please try to stay on-topic. This issue is used to track progress on the porting of features, not compatibility with various android versions. If you're encountering a problem, open a new issue.

**Comment by risjsnx** [comment]
>  Headphone surround +

what is that for ? and also i thought reverberation is done as of the latest WstXDA's build 

edit : and also isn't that the FETcompressor is also done ? since the file is already there (but maybe it has not been perfected)
